version: '3.1'

services:
         db:
            image: mysql
            restart: always
            environment:
                 MYSQL_ROOT_PASSWORD: root
                 MYSQL_DATABASE: livraria
                 MYSQL_USER: livraria
                 MYSQL_PASSWORD: livraria
            ports:
                 - "15666:3306"

         adminer:
           image: adminer
           restart: always
           ports:
                 - "12345:8080"
